#ez alapján van kulcsolva a szerver, sok minden haszálja, pl OTEL, KAFKA, spring admin szerver
spring.application.name=config-server-demo
server.port=8888
#local git repo a configoknak
spring.cloud.config.server.git.uri=file:///C:/Training/config
#deafult branch név felülcsapása
#ide az összes alkalmazás összes síkjára mehet a config
spring.cloud.config.server.git.default-label=master
