server:
  port: 8080

spring:
  application:
    name: employees-frontend
  security:
    oauth2:
      client:
        registration:
          #ha dőlt, akkor key-value map
          keycloak:
            #ennek is lehetne saját secret-je
            client-id: employees-frontend
            authorization-grant-type: authorization_code
            #ez az oauth2 provider által megengedett redirect-uri, a {baseUrl} helyére a frontend url-je kerül majd
            redirect-uri: "{baseUrl}/login/oauth2/code/"
            #megmondja, hogy a token-ben milyen adatok legyenek, ezeket a backend-en is be kell állítani
            # consent mechanism-hoz lett kitalálva, hogy a user lássa, hogy milyen adatokhoz fér hozzá az alkalmazás, saját scope-okat is létre lehet hozni a keycloak-ban, de most csak a standard scope-okat használjuk
            scope:
              - openid
              - profile
              - email
              -
      provider:
        keycloak:
          issuer-uri: http://localhost:8090/realms/EmployeesRealm

logging:
  level:
    employees: DEBUG
    org.hibernate.SQL: TRACE

employees:
  backend-url: http://localhost:8081