server:
  port: 8080

spring:
  application:
    name: employees-frontend
  cloud:
    stream:
      bindings:
        backend-request:
          destination: employees-backend-request
          content-type: application/*+avro
        employees-backend-response:
          destination: employees-backend-response
          content-type: application/*+avro
      function:
        bindings:
          employeeCreated-in-0: employees-backend-response

logging:
  level:
    employees: DEBUG
    org.hibernate.SQL: TRACE
    #lehetne a retryokat is látni a lgoban, ha debugra van állítva

employees:
  backend-url: http://localhost:8081