spring:
  application:
    name: employees-gateway
  cloud:
    gateway:
      webflux:
        routes:
          - id: employees-backend
            uri: http://localhost:8081
            predicates:
              - Path=/api/employees/**
server:
  port: 8000